config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :sauces
  resources :orders
  resources :ingredients
  resources :factories
  root 'sauces#index'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_many :sauces, :through => :factories
	has_many :factories
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.required(:ingredient).permit(:name, :cost)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(ingredient) do |f| %>
<% if ingredient.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

  <ul>
    <% ingredient.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<table id="ingredientList1">
  <%= f.hidden_field :user_id, value: current_user, class: "field" %>
  <tr>
    <td colspan="2" class="ingredientOrigin">
      <div class="newSauceField" class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
    </td>
  </tr>
  <tr>
    <td colspan="2" class="ingredientOrigin">
      <div class="newSauceField" class="field">
        <%= f.label :cost %><br>
        <%= number_field(:ingredient, :cost, in: 0.00..20.00, step:0.01) %>
      </div>
    </td>
  </tr>
  <tr>
    <td colspan="2" class="ingredientOrigin">
      <div class="newSauceField" class="actions">
        <%= f.submit %>
      </div>
    </td>
  </tr>
</table>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <th class="ingredientspace"><%= ingredient.name %></th>
        <td class="ingredientspace"><strong>Cost:</strong>$<%= ingredient.cost %></td>
        <td class="ingredientspace" class="ingredientalign"><%= link_to 'Show', ingredient %></td>
        <td class="ingredientspace" class="ingredientalign"><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td class="ingredientspace" class="ingredientalign"><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Cost:</strong>
  $<%= @ingredient.cost %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>