config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :sauces
  resources :orders
  resources :ingredients
  resources :factories
  root 'sauces#index'
end

app/models/sauce.rb
class Sauce < ApplicationRecord
  validates :image, presence: true
  belongs_to :origin, class_name:"Location"
  validates :image, :user_id, presence: true
  belongs_to :user
  has_attached_file :image, styles: { :small => "300x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_many :orders
  has_many :ingredients, :through => :factories
  has_many :factories
end

app/controllers/sauces_controller.rb
class SaucesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_sauce, only: [:show, :edit, :update, :destroy]
  before_action :owned_sauce, only: [:edit, :delete, :update]


  # GET /sauces
  # GET /sauces.json
  def index
    @sauces = Sauce.all
  end

  # GET /sauces/1
  # GET /sauces/1.json
  def show
  end

  # GET /sauces/new
  def new
    @sauce = Sauce.new
    @locations = Location.all
  end

  # GET /sauces/1/edit
  def edit
    @locations = Location.all
  end

  # POST /sauces
  # POST /sauces.json
  def create
    @sauce = Sauce.new(sauce_params)
    @locations = Location.all
    @sauce.user_id = current_user.id

    respond_to do |format|
      if @sauce.save
        format.html { redirect_to @sauce, notice: 'Sauce was successfully created.' }
        format.json { render :show, status: :created, location: @sauce }
      else
        format.html { render :new }
        format.json { render json: @sauce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sauces/1
  # PATCH/PUT /sauces/1.json
  def update
    respond_to do |format|
      if @sauce.update(sauce_params)
        format.html { redirect_to @sauce, notice: 'Sauce was successfully updated.' }
        format.json { render :show, status: :ok, location: @sauce }
      else
        format.html { render :edit }
        format.json { render json: @sauce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sauces/1
  # DELETE /sauces/1.json
  def destroy
    @sauce.destroy
    respond_to do |format|
      format.html { redirect_to sauces_url, notice: 'Sauce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sauce
      @sauce = Sauce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sauce_params
      params.require(:sauce).permit(:name, :description, :origin_id, :ingredients,:image)
    end

    def owned_sauce
      unless current_user == @sauce.user
        flash[:alert] = "This is not your post!"
        redirect_to root_path
      end
    end

end

app/helpers/sauces_helper.rb
module SaucesHelper
end

app/views/sauces/_form.html.erb
<%= form_for(sauce) do |f| %>
  <% if sauce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sauce.errors.count, "error") %> prohibited this sauce from being saved:</h2>

      <ul>
      <% sauce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table id="ingredientList1">
  <%= f.hidden_field :user_id, value: current_user, class: "field" %>
    <tr>
      <td colspan="2" class="ingredientOrigin">
        <div class="newSauceField" class="field">
          <%= f.label :image %><br>
          <%= f.file_field :image %>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="ingredientOrigin">
        <div class="newSauceField" class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="ingredientOrigin">
        <div class="newSauceField" class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description, cols:"25", rows:"10" %>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="ingredientOrigin">
        <div class="newSauceField" class="field">
          <%= f.label :origin_id %><br>
          <%= f.select :origin_id, @locations.map{|x| ["#{x.city}, #{x.state}", x.id]} %>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="ingredientOrigin">
        <div class="newSauceField" class="actions">
          <%= f.submit %>
        </div>
      </td>
    </tr>
</table>
<% end %>

app/views/sauces/edit.html.erb
<h1>Editing Sauce</h1>

<%= render 'form', sauce: @sauce %>

<%= link_to 'Show', @sauce %> |
<%= link_to 'Back', sauces_path %>

app/views/sauces/index.html.erb
<% @sauces.each do |sauce| %>
    <div class="product">
      <%=link_to new_order_path(@order) do %>
        <div class="p-image sauce_<%=sauce.id%>" style='background-image: url("<%=sauce.image%>")'></div>
      <%end%>
      <div class="p-name">
        <%= sauce.name %>
      </div>

    </div>
<% end %>

app/views/sauces/new.html.erb
<div id="newSauceForm">
<h1>New Sauce</h1>

<%= render 'form', sauce: @sauce %>

<div id="newSauceBack">
<%= link_to 'Back', sauces_path %>
</div>
</div>

app/views/sauces/show.html.erb
<p>
  <strong>Image:</strong>
  <%= image_tag @sauce.image.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @sauce.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sauce.description %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @sauce.origin.fullorigin %>
</p>

<%if @sauce.user_id == current_user.id%>
  <div class="text-center edit-links">
    <%= link_to "Edit", edit_sauce_path(@sauce) %>
    |
    <%= link_to 'Delete', @sauce, method: :delete, data: { confirm: 'Are you sure?' } %>
    |
    <%= link_to "Cancel", sauces_path%>
  </div>
<%else%>
  <div class="text-center edit-links">
    <%= link_to "Cancel", sauces_path%>
  </div>
<% end %>