config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :sauces
  resources :orders
  resources :ingredients
  resources :factories
  root 'sauces#index'
end

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-default'>
  <div class="navbar-container">
    <div class="navbar-header">
      <button type="button" name="button" class='navbar-toggle collapsed' data-target= '#bs-navbar-collapse-1' data-toggle="collapse">
        <span class='sr-only'>Toggle Navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <div class="navbar-brand">
        <%=link_to 'Hot Licks Sauces', root_path%>
      </div>
    </div>
    <div id="bs-navbar-collapse-1" class="collapse navbar-collapse">
      <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
          <li> <%=link_to "New Ingredient", new_ingredient_path%> </li>
          <li> <%=link_to "New Sauce", new_sauce_path%> </li>
          <li> <%=link_to "New Factory", new_factory_path%> </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
        <%else%>
          <li> <%=link_to "Login", new_user_session_url%> </li>
          <li> <%=link_to "Register", new_user_registration_path %> </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotSauce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>